project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "Book Title"
  output-file: main
  author: "Book Author"
  date: "01/01/0000"
  image: cover.png
  image-alt: "Book Cover"
  isbn: "978-XXX"
  license: CC-BY-4.0
  language: nl
  publisher: Konsensus Network
  favicon: /figures/freestarfish.png
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Read online"
        href: index.qmd
        aria-label: Book
      - icon: shop
        text: "Buy this book!"
        href: https://bitcoinbook.shop/products/
        aria-label: Shop
  page-footer:
    left:
      - text: "© 2024 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "Presale"
        href: presale.qmd
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/ch01.qmd
    - part: "Cos'è il denaro?"
      chapters:
        - chapters/ch02.qmd
        - chapters/ch03.qmd
        - chapters/ch04.qmd
        - chapters/ch05.qmd
        - chapters/ch06.qmd
    - part: "La nascita delle banche"
      chapters:
        - chapters/ch07.qmd
        - chapters/ch08.qmd
        - chapters/ch09.qmd
        - chapters/ch10.qmd
        - chapters/ch11.qmd
    - part: "Ascesa e caduta degli ordini monetari globali"
      chapters:
        - chapters/ch12.qmd
        - chapters/ch13.qmd
        - chapters/ch14.qmd
        - chapters/ch15.qmd
        - chapters/ch16.qmd
        - chapters/ch17.qmd
    - part: "L'entropia dei registri fiat"
      chapters:
        - chapters/ch18.qmd
        - chapters/ch19.qmd
        - chapters/ch20.qmd
        - chapters/ch21.qmd
        - chapters/ch22.qmd
        - chapters/ch23.qmd
        - chapters/ch24.qmd
    - part: "Internetmoney"
      chapters:
        - chapters/ch25.qmd
        - chapters/ch26.qmd
        - chapters/ch27.qmd
        - chapters/ch28.qmd
        - chapters/ch29.qmd
        - chapters/ch30.qmd
        - chapters/ch31.qmd
        - chapters/ch32.qmd
    - part: "Tecnologia finanziaria e diritti umani"
      chapters:
        - chapters/ch33.qmd
        - chapters/ch34.qmd
        - chapters/ch35.qmd
        - chapters/ch36.qmd
    - chapters/ch37.qmd
    - chapters/ch38.qmd

format:
  html:
    lang: it
    theme:
      light: [lux, theme.scss, theme-light.scss]
      dark: [lux, theme.scss, theme-dark.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 1em
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    lang: it
    documentclass: memoir
    classoption: smalldemyvopaper,10pt,twoside,onecolumn,openright,extrafontsizes,hidelinks
    papersize: a5
    toc-depth: 1
    toc-title: Indice
    keep-tex: true
    colorlinks: false
    include-in-header:
      - preamble.tex
  epub:
    cover-image: cover.png
    cover-image-alt: |
      Book Cover
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Indice
    lang: "it-IT"
    css: epub.css
    number-depth: 2
  docx:
    toc-depth: 1
    lang: "it-IT"
