# Riconoscimenti {.unnumbered}

Scrivere un libro di questa portata rappresenta un'impresa di notevoli dimensioni e può essere realizzato solo grazie a un sostegno immenso.

Innanzitutto, desidero esprimere la mia gratitudine a coloro che sono stati direttamente coinvolti nella realizzazione di questo libro. Mio marito, Mohamed Badran, ha fornito un supporto fondamentale nella revisione della struttura e nel feedback iniziale, contribuendo a creare un'esperienza di lettura chiara e fluida. Joakim Book, in qualità di professionista esperto di storia monetaria, ha offerto un'assistenza editoriale e di ricerca approfondita, il cui apporto ha notevolmente elevato la qualità del testo.

Nel libro sono presenti oltre 400 citazioni, nonché innumerevoli persone, passate e presenti, il cui lavoro ha influenzato la sua genesi. È fondamentale sottolineare che considero opere con cui non condivido l'opinione altrettanto significative, dal punto di vista della ricerca, quanto quelle con cui concordo. Questi scritti, infatti, contribuiscono a mettere alla prova le idee e a affinare le conclusioni. Poiché non posso menzionarle tutte specificamente in questo contesto, invito il lettore a consultare le note a piè di pagina e la bibliografia. Sono profondamente grato per tutti i materiali pubblicati, frutto del lavoro di tanti, che ho avuto l'opportunità di citare in quest'opera o dai quali ho tratto ispirazione.

Oltre ai celebri scrittori storici che hanno influenzato ogni aspetto del nostro pensiero, vi sono anche alcuni autori contemporanei, investitori, umanitari e leader d'impresa il cui lavoro è stato tra i più citati o ha esercitato una notevole influenza su questo libro. Tra questi si annoverano Alex Gladstein, Ray Dalio, Stanley Druckenmiller, Barry Eichengreen, George Selgin, Luke Gromen, Saifedean Ammous, Nick Szabo, Adam Back, Elizabeth Stark, Michael Saylor, Jeff Booth, John Pfeffer, Caitlin Long, Gigi, Nic Carter, Obi Nwosu, Yan Pritzker e Anita Posch.

Tutti i proventi delle prime mille copie vendute saranno devoluti alla Human Rights Foundation, la quale, oltre a fornire supporto a persone bisognose, si è rivelata una preziosa fonte di ricerca per il mio lavoro.

# Introduzione

Nel settembre del 2022, un gruppo di persone comuni ha preso d'assalto diverse banche in Libano.

Ciò che rese questi eventi più rilevanti dal punto di vista mediatico rispetto ai classici furti in banca fu il fatto che la maggior parte dei protagonisti stava semplicemente tentando di recuperare i propri soldi. A causa di una crisi finanziaria in Libano, le banche avevano negato l'accesso ai depositi monetari ai propri clienti per un lungo periodo di tempo.

Uno dei "ladri di banca" che ha catturato l'attenzione dei media è stata una giovane donna, lavoratrice nel campo dell'interior design. Durante una rapina in una banca di Beirut, ha minacciato il personale utilizzando quella che si rivelò poi essere una pistola finta dal aspetto molto realistico, con l'intento di prelevare i risparmi della sua famiglia necessari per il trattamento della sorella malata di cancro, poiché tali risparmi erano stati congelati dall'istituto bancario. Questo episodio è forse l'esempio più eclatante, ma in quel periodo si sono verificate numerose altre rapine da parte di persone che desideravano soltanto riavere i propri depositi. Alcuni di questi individui, infatti, hanno fatto ricorso a vere armi.

Questi eventi in Libano, sebbene specifici a un determinato paese e periodo, si inseriscono all'interno di una narrazione globale.

La Nigeria, un paese con oltre 200 milioni di abitanti, ha registrato un'inflazione annuale del 13% nell'ultimo decennio. Nel 2021, è stata lanciata una valuta digitale centralizzata, conosciuta come eNaira, che finora ha avuto un'adozione estremamente bassa. Al contrario, le criptovalute, in particolare il bitcoin e le stablecoin collegate al dollaro statunitense, hanno visto un tasso di adozione di gran lunga superiore nel paese, nonostante il sistema bancario nigeriano fosse di fatto inaccessibile. In risposta a questa situazione, il governo nigeriano ha implementato una serie di politiche destinate a ridurre la disponibilità di contante fisico e promuovere la transizione verso i pagamenti digitali, contribuendo così a un periodo di turbolenza politica e disordini civili.

Nel autunno del 2016, l'Egitto ha drasticamente dimezzato il valore della sua valuta rispetto al dollaro statunitense, un provvedimento che ha annientato anni di risparmi per una popolazione di circa 100 milioni di persone. Nel 2022 e nel 2023, il paese ha attuato ulteriori e brusche svalutazioni della sua valuta rispetto al dollaro, portando a un ulteriore dimezzamento del tasso di cambio. Conosco persone in Egitto che acquistano dollari statunitensi fisici nel mercato nero e li conservano come forma di protezione contro questo persistente problema. Per effettuare tali operazioni, devono affrontare significative commissioni di cambio, senza guadagnare interessi sui dollari cartacei detenuti. Quando si verificano queste svalutazioni, il peso del problema ricade immediatamente su tutti i lavoratori del paese, che si trovano nella necessità di negoziare aumenti salariali per recuperare parte del potere d'acquisto perso, dal momento che le loro retribuzioni sono espresse nella valuta locale svalutata.

La Turchia e l'Argentina, entrambe membri del G20 e con una popolazione complessiva che supera i 130 milioni di abitanti, hanno affrontato negli ultimi anni un'inflazione fuori controllo. Nel 2022, la Turchia ha registrato un'inflazione annua del 85%, mentre nel 2023 l'Argentina ha superato abbondantemente il 100% di inflazione. [^2]

Negli anni '90, il Brasile ha attraversato un periodo di iperinflazione, mentre si trovava a essere il quinto paese più popoloso al mondo. Quando si pensa all'iperinflazione, si tendono a evocare immagini della Germania degli anni '20 o di stati falliti nel contesto attuale, ma sorprendentemente, un numero significativo di paesi ha vissuto quella condizione in un momento o nell'altro durante la seconda metà del XX secolo. A partire dagli anni '80 fino ad oggi, cittadini di Brasile, Argentina, Jugoslavia, Zimbabwe, Venezuela, Polonia, Kazakistan, Peru, Bielorussia, Bulgaria, Ucraina, Libano e molti altri paesi hanno subito l'iperinflazione. Inoltre, nazioni come Israele, Messico, Vietnam, Ecuador, Costa Rica e Turchia hanno vissuto tassi di inflazione a tre cifre (ossia quasi iperinflazione) nel medesimo arco temporale.

Dal 2016 al 2021, molti mercati obbligazionari sovrani delle nazioni più ricche, in Europa e in Giappone, offrivano rendimenti nominali vicini allo zero o addirittura negativi, raggiungendo un picco di oltre 18 trilioni di dollari in obbligazioni con rendimento negativo. [^^3] In tal contesto, i creditori erano costretti a pagare per il privilegio di prestare denaro a governi e grandi corporazioni, piuttosto che ricevere interessi per farlo. Gli incentivi all'interno del sistema finanziario risultarono così completamente capovolti. Negli anni successivi, una forte ondata di inflazione globale ridusse gravemente il potere d'acquisto dei detentori di tali obbligazioni.

Nel corso degli anni 2010, diversi membri di alto livello della Federal Reserve degli Stati Uniti hanno reiterato che l'economia era rimasta al di sotto del loro obiettivo medio di inflazione per un periodo eccessivamente lungo e che desideravano un'inflazione più elevata. Durante un'audizione congressuale all'inizio del 2021, quando il tasso di inflazione statunitense si attestava a solo l'1,7%, il presidente della Federal Reserve è stato interpellato da un congressista riguardo l'impennata del 25% dell'offerta di moneta complessiva rispetto all'anno precedente (il tasso più elevato dai anni '40), verificatasi a causa delle recenti misure di stimolo fiscale, e sulle potenziali implicazioni che questo fenomeno potesse avere sull'inflazione o sul valore del dollaro. Il presidente ha liquidato queste preoccupazioni, affermando che un aumento così marcato dell'offerta di moneta probabilmente non avrebbe avuto importanti ripercussioni economiche e che sarebbe necessario "disimparare" l'idea che gli aggregati monetari abbiano un impatto significativo sull'economia. [^4]

Con l'emergere dell'inflazione dei prezzi, che si fece seriamente sentire alla fine del 2021, il presidente della Federal Reserve inizialmente minimizzò la situazione, considerandola transitoria, mentre la banca continuava ad espandere l'offerta di moneta di base attraverso il quantitative easing. Tuttavia, con l'innalzarsi dei tassi di inflazione ai livelli più alti degli ultimi quarant'anni nel 2022, il presidente e altri dirigenti della Federal Reserve entrarono in panico, cambiando radicalmente la loro politica monetaria e definendo l'inflazione dei prezzi come il problema principale da affrontare. Nel tentativo di contenere questa inflazione, aumentarono i tassi d'interesse in modo così aggressivo e ridussero l'offerta di moneta di base a un ritmo record nell'arco dell'anno successivo, che finirono per generare oltre un trilione di dollari di perdite non realizzate per le banche sui loro titoli del Tesoro e altri attivi a basso rischio. Questa draconiana sottrazione di depositi dal sistema bancario contribuì a provocare alcune delle più grandi crisi bancarie nella storia americana. Nel 2023, le banche di tutto il paese riportavano rapporti patrimoniali severamente compromessi a causa dell'improvviso aumento dei tassi d'interesse. Per la prima volta nella storia moderna, anche la stessa Federal Reserve si trovava a gestire una perdita operativa, dovuta agli elevati tassi d'interesse pagati sulle proprie passività rispetto agli introiti derivanti dai suoi attivi. [^^5] Queste decisioni della Federal Reserve influenzano le condizioni monetarie per 330 milioni di americani e miliardi di persone in altri paesi, eppure sono adottate manualmente e soggettivamente da un gruppo di sole dodici persone.

Nel mondo esistono circa 160[^6] valute diverse, ognuna con un monopolio locale all'interno della propria giurisdizione, e la maggior parte di esse ha scarsa o addirittura nulla accettazione al di fuori di tale contesto. A questo riguardo, l'ordine finanziario globale si configura quasi come un sistema di baratto. Solo alcune valute principali sono detenute come valute di riserva da altre banche centrali e godono di un certo grado di accettazione internazionale, ma tendono a perdere valore lentamente nel tempo e presentano tassi d'interesse che non riescono a mantenere il passo con l'inflazione da anni. Le altre valute, invece, sono più soggette a brusche svalutazioni, a periodi prolungati di inflazione a due cifre e a occasionali iperinflazioni, rimanendo, spesso, con scarsa o nulla accettazione all'estero. Per le persone provenienti da paesi appartenenti a questa seconda categoria, è comune cercare di ottenere valute estere, come i dollari, per proteggere i propri risparmi, poiché in genere non possono fidarsi delle banche locali per gestirle.

Risparmiare denaro può rappresentare una vera sfida, anche nelle giurisdizioni monetarie più stabili; e se una persona nasce nella 'giurisdizione sbagliata', l'ostacolo diventa ancora più arduo da superare.

Come abbiamo raggiunto questo punto? Perché il nostro denaro non è migliore di così?

Il sistema finanziario globale si è rivelato difettoso per i paesi in via di sviluppo per tutta la durata della storia moderna, e negli ultimi decenni ha accumulato gravi squilibri anche per le nazioni sviluppate. Le fondamenta su cui si regge non sono più solide, in parte a causa dell'obsolescenza della sua tecnologia di base.

Sostengo che l'ascesa del populismo negli Stati Uniti, in Europa e in diversi paesi in via di sviluppo, iniziata dopo la crisi finanziaria globale del 2008, sia in gran parte riconducibile a questo fenomeno. Sia a sinistra che a destra dell'asse politico, le persone avvertono che qualcosa non va, che il sistema è 'manipolato' a loro sfavore, ma non riescono a comprendere appieno le ragioni di questa percezione. Un elemento cruciale di questa situazione è rappresentato dal fatto che il sistema finanziario così come lo conosciamo non funziona più.

Negli anni precedenti, abbiamo assistito al progressivo disfacimento degli ordini finanziari globali a causa dell'accumularsi di squilibri economici, dell'emergere di riallineamenti geopolitici e dell'introduzione di nuove tecnologie. Quando si verifica questa situazione, l'ordine precedente viene in parte o completamente ricostruito e trasformato in un nuovo assetto, con esempi di tali eventi che possono essere rintracciati nel presente volume. La maggior parte dei segnali attuali suggerisce che l'ordine finanziario vigente sin dagli anni '70 sta giungendo al termine e ha avviato un processo di ricostruzione e riallineamento.

Questo volume esplora il concetto di denaro attraverso il prisma dei progressi tecnologici. Analizza l'evoluzione del denaro nel corso della storia, le ragioni per cui le attuali tecnologie e istituzioni monetarie non riescono a soddisfare le nostre esigenze contemporanee e presenta alcune possibili soluzioni ai problemi monetari che ci troviamo ad affrontare. Scritto in un linguaggio chiaro, il libro è organizzato in modo modulare, consentendo ai lettori di concentrarsi sugli aspetti che suscitano maggiormente il loro interesse.

La prima parte del libro guida il lettore attraverso i registri antichi e le monete merce, per analizzare le ragioni per cui il denaro è emerso in modo naturale e perché alcune forme di denaro abbiano superato le altre. Questo ci permette di discernere quali siano le proprietà ideali del denaro e perché queste tendano a ripresentarsi nel corso della storia in modo autonomo. Inoltre, esplora il rapporto tra credito sociale e moneta merce, offrendo un'opportunità di riconciliazione tra due scuole di pensiero economiche che spesso si trovano in conflitto.

La seconda parte del libro affronta i primi servizi proto-bancari e l'emergere delle banche a servizio completo. Analizza come i molteplici sviluppi tecnologici abbiano accelerato le transazioni monetarie, distogliendole dal più lento processo di regolamento monetario fisico. Sebbene questa evoluzione abbia comportato numerosi vantaggi, ha presentato anche alcune criticità. Il capitolo si conclude esaminando come l'incremento della disparità di velocità tra transazioni e regolamenti, in concomitanza con l'avvento dell'era delle telecomunicazioni, abbia conferito un notevole potere alle banche e alle banche centrali, che sono diventate le principali entità in grado di trasmettere rapidamente denaro in tutto il mondo.

La terza parte del libro analizza il sistema finanziario globale come è stato strutturato sin dai primi del XX secolo, esaminando anche le geopolitiche che ne hanno guidato la creazione e le sue evoluzioni nel corso del tempo. Viene trattato il periodo di fallimento dei legami con l'oro, che si è verificato durante la Prima Guerra Mondiale, il sistema di Bretton Woods, operante dagli anni '40 fino ai primi anni '70, e il sistema Eurodollaro/Petrodollaro che lo ha sostituito dalla metà degli anni '70 fino ad oggi. Infine, si mette in luce come alcune problematiche legate all'attuale versione del sistema abbiano generato squilibri strutturali a livello globale negli ultimi decenni.

La quarta parte del libro analizza nel dettaglio il processo di creazione del denaro all'interno del moderno sistema finanziario e come il debito, per sua natura, tenda a destabilizzare il sistema nel tempo. Si esaminano anche alcuni degli squilibri e degli incentivi problematici derivanti dalla continua svalutazione delle unità monetarie, poiché i risparmiatori cercano di preservare il proprio potere d'acquisto investendo in altri beni non monetari. Inoltre, si illustra come i legislatori siano stati dotati di un registro pubblico flessibile che consente di intraprendere azioni di guerra senza ricorrere alla tassazione, di effettuare salvataggi selettivi tramite la svalutazione dei risparmi di altre persone e, in generale, di finanziare le spese in modi poco trasparenti.

La quinta parte esamina le innovazioni monetarie digitali del XXI secolo, includendo Bitcoin, stablecoin, contratti intelligenti e valute digitali delle banche centrali. Questa sezione del libro è la più speculativa, poiché si concentra sul presente e sul futuro piuttosto che sul passato. Vengono descritti alcuni delle nuove tecnologie a nostra disposizione, approfondendo in particolare i vari compromessi e rischi ad esse associati, accanto alle opportunità che possono offrire.

La sesta parte del libro esamina l'etica del denaro e della comunicazione, due elementi fondamentali del commercio. Viene analizzato il ruolo della crittografia in generale, considerata un aspetto imprescindibile dell'infrastruttura bancaria moderna e di internet. Si discute, inoltre, la differenza tra reti finanziarie aperte e chiuse e l'intersezione tra tecnologia finanziaria e diritti umani.

Alla sua essenza, il denaro rappresenta un registro. Il denaro merce funge da registro regolato dalla natura, mentre il denaro bancario agisce come un registro controllato dagli stati nazionali. Infine, il denaro open-source si configura come un registro gestito dagli utenti stessi. Come viene esplorato nel libro, l'evoluzione della tecnologia modifica le strutture di potere e gli incentivi prevalenti legati al denaro, trasformandoli di epoca in epoca.

Il mio background combina ingegneria e finanza, e adotto un approccio di ingegneria dei sistemi nell'analizzare i vari aspetti del sistema finanziario globale. L'ingegneria dei sistemi è un campo multidisciplinare che si concentra sulla progettazione, integrazione, operatività e manutenzione di sistemi complessi nel corso del loro ciclo di vita. Considero il sistema finanziario globale come un sistema ingegnerizzato, e ho scoperto che questo metodo di analisi porta a conclusioni innovative che talvolta mettono in discussione il pensiero economico tradizionale.

Il mio obiettivo nella scrittura di questo libro è fornire una comprensione più profonda del funzionamento del denaro e delle ragioni per cui il sistema finanziario globale non opera più con la stessa efficienza di un tempo. Non si tratta solo di esaminare le problematiche attuali che affliggono il nostro sistema finanziario in questo anno o in questo decennio, ma di intraprendere un'analisi più approfondita su cosa sia realmente il denaro, come siamo arrivati alla situazione attuale e quali siano i problemi fondamentali che ci troviamo ad affrontare.

Non ho tutte le risposte e non sono in grado di prevedere come sarà il mondo della finanza nei decenni a venire. Tuttavia, il mio obiettivo in questo libro è condividere le mie ricerche affinché i lettori possano sentirsi maggiormente in grado di trovare risposte per se stessi. La politica può influenzare gli eventi a livello locale e temporaneo, mentre la tecnologia ha il potere di apportare cambiamenti a livello globale e duraturo. È per questo motivo che analizzo il denaro soprattutto attraverso la lente della tecnologia.

Questo non è un libro dedicato all'oro, alle banche, al bitcoin o alla politica. Somiglia piuttosto a un'analisi delle tecnologie monetarie nelle loro molteplici manifestazioni, che abbraccia il passato, il presente e il futuro. Attraverso l'esplorazione di questi temi e di altri ancora, ci proponiamo di comprendere meglio le nostre origini e i possibili percorsi che ci attendono nel futuro.
